version: "3.7"

networks:
  new_network:
    driver: bridge

volumes: 
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: /home/cshelli/data/wordpress
  mariadb:
    driver_opts:
      type: none
      o: bind
      device: /home/cshelli/data/db

services:
  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
        - 443:443
    volumes:
        - wordpress:/var/www/html/
    networks:
        - new_network
    restart: always
  wordpress:
    depends_on:
        - mariadb
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    # ports: 
    #     - 9000:9000
    volumes:
        - wordpress:/var/www/html/
    networks:
        - new_network
    env_file:
        - .env
    restart: always
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    # ports:
    #     - 3306:3306
    networks:
        - new_network
    volumes:
        - mariadb:/var/lib/mysql
    env_file:
        - .env
    restart: always